Case When exists (Select * From syscolumn inner join systable on syscolumn.table_id = systable.table_id where systable.table_name = 't_optiongen' and syscolumn.column_name = 'traiturg') Then ALTER TABLE t_optiongen ALTER traiturg integer end;

Case When not exists(select 1 from systable where table_name = 't_protocoleurgent_cegep') then 
		CREATE TABLE t_protocoleurgent_cegep (	
			id_protocoleurgent_cegep integer NOT NULL DEFAULT autoincrement,	
			date_protocoleurgent date ,	
			id_patient integer ,	
			depistage integer ,	
			datebarre date NULL,	
			sec_1_visage_peau integer DEFAULT 0,	
			sec_1_visage_peau_desc varchar(50) NULL,	
			sec_1_atm integer DEFAULT 0,	
			sec_1_atm_desc varchar(50) NULL,	
			sec_1_ganglions integer DEFAULT 0,	
			sec_1_ganglions_desc varchar(50) NULL,	
			sec_1_parotide integer DEFAULT 0,	
			sec_1_parotide_desc varchar(50) NULL,	
			sec_1_thyroides integer DEFAULT 0,	
			sec_1_thyroides_desc varchar(50) NULL,	
			sec_1_autres varchar(250) NULL, 	
			sec_2_levres integer default 0, 	
			sec_2_levres_desc varchar(50) null, 	
			sec_2_muqueuses integer default 0, 	
			sec_2_muqueuses_desc varchar(50) null, 	
			sec_2_vestibule integer default 0, 	
			sec_2_vestibule_desc varchar(50) null, 	
			sec_2_plancher_buccal integer default 0, 	
			sec_2_plancher_buccal_desc varchar(50) null, 	
			sec_2_langue integer default 0, 	
			sec_2_langue_desc varchar(50) null, 	
			sec_2_crete integer default 0, 	
			sec_2_crete_desc varchar(50) null, 	
			sec_2_palais_dur integer default 0, 	
			sec_2_palais_dur_desc varchar(50) null, 	
			sec_2_palais_mou integer default 0, 	
			sec_2_palais_mou_desc varchar(50) null, 	
			sec_2_oropharynx integer default 0, 	
			sec_2_oropharynx_desc varchar(50) null, 	
			sec_2_plancher integer default 0, 	
			sec_2_plancher_desc varchar(50) null, 	
			sec_2_autres varchar(100) null, 	
			sec_2_a varchar(100) null, 	
			sec_2_b varchar(100) null, 	
			sec_2_c varchar(100) null, 	
			sec_2_d1 integer default 0, 	
			sec_2_d2 integer default 0, 	
			sec_2_t varchar(100) null, 	
			sec_3_demineralisation integer DEFAULT 0, 	
			sec_3_demineralisation_desc varchar(50) NULL, 	
			sec_3_hypocalcification integer DEFAULT 0, 	
			sec_3_hypocalcification_desc varchar(50) NULL, 	
			sec_3_hypoplasie integer DEFAULT 0, 	
			sec_3_hypoplasie_desc varchar(50) NULL, 	
			sec_3_attrition integer DEFAULT 0, 	
			sec_3_attrition_desc varchar(50) NULL, 	
			sec_3_abrasion integer DEFAULT 0, 	
			sec_3_abrasion_desc varchar(50) NULL, 	
			sec_3_abfraction integer DEFAULT 0, 	
			sec_3_abfraction_desc varchar(50) NULL, 	
			sec_3_erosion integer DEFAULT 0, 	
			sec_3_erosion_desc varchar(50) NULL, 	
			sec_3_autres varchar(250) NULL, 	
			sec_3_cambra_niveau integer DEFAULT 0, 	
			sec_4_profil integer DEFAULT 0, 	
			sec_4_classe integer DEFAULT 0, 	
			sec_4_surplombs_perc Decimal(5,2) DEFAULT 0, 	
			sec_4_surplombs_mm integer DEFAULT 0, 	
			sec_4_ligne_mediane varchar(50) NULL, 	
			sec_4_malrelations integer DEFAULT 0, 	
			sec_4_chevauchement1 varchar(1) NULL, 	
			sec_4_chevauchement2 varchar(1) NULL, 	
			sec_4_chevauchement3 varchar(1) NULL, 	
			sec_4_chevauchement4 varchar(1) NULL, 	
			sec_4_chevauchement5 varchar(1) NULL, 	
			sec_4_chevauchement6 varchar(1) NULL, 	
			sec_4_rotations1 varchar(1) NULL, 	
			sec_4_rotations2 varchar(1) NULL, 	
			sec_4_rotations3 varchar(1) NULL, 	
			sec_4_rotations4 varchar(1) NULL, 	
			sec_4_rotations5 varchar(1) NULL, 	
			sec_4_rotations6 varchar(1) NULL, 	
			sec_4_buccale1 varchar(1) NULL, 	
			sec_4_buccale2 varchar(1) NULL, 	
			sec_4_buccale3 varchar(1) NULL, 	
			sec_4_buccale4 varchar(1) NULL, 	
			sec_4_buccale5 varchar(1) NULL, 	
			sec_4_buccale6 varchar(1) NULL, 	
			sec_4_linguale1 varchar(1) NULL, 	
			sec_4_linguale2 varchar(1) NULL, 	
			sec_4_linguale3 varchar(1) NULL, 	
			sec_4_linguale4 varchar(1) NULL, 	
			sec_4_linguale5 varchar(1) NULL, 	
			sec_4_linguale6 varchar(1) NULL, 	
			sec_4_distale1 varchar(1) NULL, 	
			sec_4_distale2 varchar(1) NULL, 	
			sec_4_distale3 varchar(1) NULL, 	
			sec_4_distale4 varchar(1) NULL, 	
			sec_4_distale5 varchar(1) NULL, 	
			sec_4_distale6 varchar(1) NULL, 	
			sec_4_mesiale1 varchar(1) NULL, 	
			sec_4_mesiale2 varchar(1) NULL, 	
			sec_4_mesiale3 varchar(1) NULL, 	
			sec_4_mesiale4 varchar(1) NULL, 	
			sec_4_mesiale5 varchar(1) NULL, 	
			sec_4_mesiale6 varchar(1) NULL, 	
			sec_4_espace integer DEFAULT 0, 	
			sec_5_tache integer DEFAULT 0, 	
			sec_5_ind_plaq Decimal(5,2) DEFAULT 0, 	
			sec_5_anterieure1 varchar(1) NULL, 	
			sec_5_anterieure2 varchar(1) NULL, 	
			sec_5_anterieure3 varchar(1) NULL, 	
			sec_5_anterieure4 varchar(1) NULL, 	
			sec_5_anterieure5 varchar(1) NULL, 	
			sec_5_anterieure6 varchar(1) NULL, 	
			sec_5_posterieure1 varchar(1) NULL, 	
			sec_5_posterieure2 varchar(1) NULL, 	
			sec_5_posterieure3 varchar(1) NULL, 	
			sec_5_posterieure4 varchar(1) NULL, 	
			sec_5_posterieure5 varchar(1) NULL, 	
			sec_5_posterieure6 varchar(1) NULL, 	
			sec_5_1_3_cervical1 varchar(1) NULL, 	
			sec_5_1_3_cervical2 varchar(1) NULL, 	
			sec_5_1_3_cervical3 varchar(1) NULL, 	
			sec_5_1_3_cervical4 varchar(1) NULL, 	
			sec_5_1_3_cervical5 varchar(1) NULL, 	
			sec_5_1_3_cervical6 varchar(1) NULL, 	
			sec_5_1_3_moyen1 varchar(1) NULL, 	
			sec_5_1_3_moyen2 varchar(1) NULL, 	
			sec_5_1_3_moyen3 varchar(1) NULL, 	
			sec_5_1_3_moyen4 varchar(1) NULL, 	
			sec_5_1_3_moyen5 varchar(1) NULL, 	
			sec_5_1_3_moyen6 varchar(1) NULL, 	
			sec_5_interproximale1 varchar(1) NULL, 	
			sec_5_interproximale2 varchar(1) NULL, 	
			sec_5_interproximale3 varchar(1) NULL, 	
			sec_5_interproximale4 varchar(1) NULL, 	
			sec_5_interproximale5 varchar(1) NULL, 	
			sec_5_interproximale6 varchar(1) NULL, 	
			sec_5_adherante1 varchar(1) NULL, 	
			sec_5_adherante2 varchar(1) NULL, 	
			sec_5_adherante3 varchar(1) NULL, 	
			sec_5_adherante4 varchar(1) NULL, 	
			sec_5_adherante5 varchar(1) NULL, 	
			sec_5_adherante6 varchar(1) NULL, 	
			sec_5_legere1 varchar(1) NULL, 	
			sec_5_legere2 varchar(1) NULL, 	
			sec_5_legere3 varchar(1) NULL, 	
			sec_5_legere4 varchar(1) NULL, 	
			sec_5_legere5 varchar(1) NULL, 	
			sec_5_legere6 varchar(1) NULL, 	
			sec_5_materia_alba1 varchar(1) NULL, 	
			sec_5_materia_alba2 varchar(1) NULL, 	
			sec_5_materia_alba3 varchar(1) NULL, 	
			sec_5_materia_alba4 varchar(1) NULL, 	
			sec_5_materia_alba5 varchar(1) NULL, 	
			sec_5_materia_alba6 varchar(1) NULL, 	
			sec_5_tartre_supra integer DEFAULT 0, 	
			sec_5_tartre_sous integer DEFAULT 0, 	
			sec_5_classe  integer DEFAULT 0, 	
			sec_6_P_type integer DEFAULT 0, 	
			sec_6_P_type_desc varchar(50) NULL, 	
			sec_6_P_cause integer DEFAULT 0, 	
			sec_6_P_annee integer DEFAULT 0, 	
			sec_6_P_autre varchar(250) NULL, 	
			sec_6_C_type integer DEFAULT 0, 	
			sec_6_C_type_desc varchar(50) NULL, 	
			sec_6_C_cause integer DEFAULT 0, 	
			sec_6_C_annee integer DEFAULT 0, 	
			sec_6_C_autre varchar(250) NULL, 	
			sec_7_biofilm integer DEFAULT 0, 	
			sec_7_papillaire integer DEFAULT 0, 	
			sec_7_marginale integer DEFAULT 0, 	
			sec_7_diffuse integer DEFAULT 0, 	
			sec_7_localisee integer DEFAULT 0, 	
			sec_7_generalisee integer DEFAULT 0, 	
			sec_7a_rose1 integer DEFAULT 0, 	
			sec_7a_rose2 integer DEFAULT 0, 	
			sec_7a_rose3 integer DEFAULT 0, 	
			sec_7a_rose4 integer DEFAULT 0, 	
			sec_7a_rose5 integer DEFAULT 0, 	
			sec_7a_rose6 integer DEFAULT 0, 	
			sec_7a_rouge1 integer DEFAULT 0, 	
			sec_7a_rouge2 integer DEFAULT 0, 	
			sec_7a_rouge3 integer DEFAULT 0, 	
			sec_7a_rouge4 integer DEFAULT 0, 	
			sec_7a_rouge5 integer DEFAULT 0, 	
			sec_7a_rouge6 integer DEFAULT 0, 	
			sec_7a_blanchatre1 integer DEFAULT 0, 	
			sec_7a_blanchatre2 integer DEFAULT 0, 	
			sec_7a_blanchatre3 integer DEFAULT 0, 	
			sec_7a_blanchatre4 integer DEFAULT 0, 	
			sec_7a_blanchatre5 integer DEFAULT 0, 	
			sec_7a_blanchatre6 integer DEFAULT 0, 	
			sec_7a_hyperplasique1 integer DEFAULT 0, 	
			sec_7a_hyperplasique2 integer DEFAULT 0, 	
			sec_7a_hyperplasique3 integer DEFAULT 0, 	
			sec_7a_hyperplasique4 integer DEFAULT 0, 	
			sec_7a_hyperplasique5 integer DEFAULT 0, 	
			sec_7a_hyperplasique6 integer DEFAULT 0, 	
			sec_7a_sain integer DEFAULT 0, 	
			sec_7b_psr integer DEFAULT 0, 	
			sec_7b_psr_1 integer DEFAULT 0, 	
			sec_7b_psr_2 integer DEFAULT 0, 	
			sec_7b_psr_3 integer DEFAULT 0, 	
			sec_7b_psr_4 integer DEFAULT 0, 	
			sec_7b_psr_5 integer DEFAULT 0, 	
			sec_7b_psr_6 integer DEFAULT 0, 	
			sec_7b_saignement integer DEFAULT 0, 	
			sec_7b_saignement_moins integer DEFAULT 0, 	
			sec_7b_hyperplasie integer DEFAULT 0, 	
			sec_7b_opercule integer DEFAULT 0, 	
			sec_7b_hypertrophie integer DEFAULT 0, 	
			sec_7c_cambra_selection_radiologique integer DEFAULT 0, 	
			sec_7c_consentement_do integer DEFAULT 0, 	
			sec_7c_consentement_scellements integer DEFAULT 0, 	
			sec_7c_reference_dentaire integer DEFAULT 0, 	
			sec_8_date date , 	
			sec_8_aucune_annotation integer DEFAULT 0, 	
			sec_8_bw integer DEFAULT 0, 	
			sec_8_bw_desc varchar(50) NULL, 	
			sec_8_pa integer DEFAULT 0, 	
			sec_8_pa_desc varchar(50) NULL, 	
			sec_8_panoramique integer DEFAULT 0, 	
			sec_8_panoramique_desc varchar(50) NULL, 	
			sec_8_comp_rx_ant integer DEFAULT 0, 	
			sec_8_annee_de integer DEFAULT 0, 	
			sec_8_annee_au integer DEFAULT 0, 	
			sec_8a_dents_incluses integer DEFAULT 0, 	
			sec_8a_dents_incluses_desc varchar(50) NULL, 	
			sec_8a_lesions_carieuses integer DEFAULT 0, 	
			sec_8a_lesions_carieuses_desc varchar(50) NULL, 	
			sec_8a_lesions_apicales integer DEFAULT 0, 	
			sec_8a_lesions_apicales_desc varchar(50) NULL, 	
			sec_8a_obt_defectueuses integer DEFAULT 0, 	
			sec_8a_obt_defectueuses_desc varchar(50) NULL, 	
			sec_8a_autres integer DEFAULT 0, 	
			sec_8a_autres_desc varchar(250) NULL, 	
			sec_8b_dents_absentes integer DEFAULT 0, 	
			sec_8b_dents_absentes_4 integer DEFAULT 0, 	
			sec_8b_dents_absentes_5 integer DEFAULT 0, 	
			sec_8b_perte_osseuse integer DEFAULT 0, 	
			sec_8b_resorption_h integer DEFAULT 0, 	
			sec_8b_resorption_v integer DEFAULT 0, 	
			sec_8b_elargissement_du_ligament integer DEFAULT 0, 	
			sec_8b_elargissement_du_ligament_desc varchar(50) NULL, 	
			sec_8b_atteinte_furcation integer DEFAULT 0, 	
			sec_8b_atteinte_furcation_desc varchar(50) NULL, 	
			sec_8b_absence_lamina_dura integer DEFAULT 0, 	
			sec_8b_absence_lamina_dura_desc varchar(50) NULL, 	
			sec_8b_resorption_peri_implantaire integer DEFAULT 0, 	
			sec_8b_resorption_peri_implantaire_desc varchar(50) NULL, 	
			sec_8b_defaut_crete integer DEFAULT 0, 	
			sec_8b_defaut_crete_desc varchar(50) NULL, 	
			sec_8b_autres integer DEFAULT 0, 	
			sec_8b_autres_desc varchar(50) NULL, 	
			sec_8c_condyle integer DEFAULT 0, 	
			sec_8c_condyle_desc varchar(50) NULL, 	
			sec_8c_maxillaire integer DEFAULT 0, 	
			sec_8c_maxillaire_desc varchar(50) NULL, 	
			sec_8c_sinus integer DEFAULT 0, 	
			sec_8c_sinus_desc varchar(50) NULL, 	
			sec_8c_mandibule integer DEFAULT 0, 	
			sec_8c_mandibule_desc varchar(50) NULL, 	
			sec_8c_autres integer DEFAULT 0, 	
			sec_8c_autres_desc varchar(250) NULL, 	
			eval1_tabagisme integer DEFAULT 0, 	
			eval1_saignement integer DEFAULT 0, 	
			eval1_medication_causant_hyperplasie integer DEFAULT 0, 	
			eval1_osteoporose integer DEFAULT 0, 	
			eval1_stress integer DEFAULT 0, 	
			eval1_xerostomie integer DEFAULT 0, 	
			eval1_facteurs_economiques integer DEFAULT 0, 	
			eval1_hyg_pauvre integer DEFAULT 0, 	
			eval1_facteurs_hormonaux integer DEFAULT 0, 	
			eval1_presence_bacteries_pathogenes integer DEFAULT 0, 	
			eval1_alimentation integer DEFAULT 0, 	
			eval1_pathogenese_specifique integer DEFAULT 0, 	
			eval1_maladie_systemique integer DEFAULT 0, 	
			eval2_age integer DEFAULT 0, 	
			eval2_heredite integer DEFAULT 0, 	
			eval2_desordres_genetiques integer DEFAULT 0, 	
			eval2_genre integer DEFAULT 0, 	
			eval2_antecedent_parodontaux integer DEFAULT 0, 	
			eval2_nationalite integer DEFAULT 0, 	
			eval3_restauration_debordante integer DEFAULT 0, 	
			eval3_prothese_mal_adaptee integer DEFAULT 0, 	
			eval3_foulage integer DEFAULT 0, 	
			eval3_anatomie_dentaire integer DEFAULT 0, 	
			eval3_debris_alimentaire integer DEFAULT 0, 	
			eval3_respirateur_buccal integer DEFAULT 0, 	
			eval3_lesion_carieuse integer DEFAULT 0, 	
			eval3_fremitus integer DEFAULT 0, 	
			eval3_couronne_mal_adaptee integer DEFAULT 0, 	
			eval3_traumatisme_occ integer DEFAULT 0, 	
			eval3_bijoux integer DEFAULT 0, 	
			eval3_malposition_point_contact integer DEFAULT 0, 	
			eval3_defaut_muco_gingivaux integer DEFAULT 0, 	
			eval3_tartre integer DEFAULT 0, 	
			eval3_atteinte_de_furc integer DEFAULT 0, 	
			eval3_orthodontie integer DEFAULT 0, 	
			eval4_parodontale_perte_support   integer DEFAULT 0, 	
			eval4_atteinte_necrosante  integer DEFAULT 0, 	
			eval4_localisee  integer DEFAULT 0, 	
			eval4_generalisee  integer DEFAULT 0, 	
			eval4_grade_a1 integer DEFAULT 0, 	
			eval4_grade_a2 integer DEFAULT 0, 	
			eval4_grade_a3 integer DEFAULT 0, 	
			eval4_grade_a4 integer DEFAULT 0, 	
			eval4_grade_b1 integer DEFAULT 0, 	
			eval4_grade_b2 integer DEFAULT 0, 	
			eval4_grade_b3 integer DEFAULT 0, 	
			eval4_grade_b4 integer DEFAULT 0, 	
			eval4_grade_c1 integer DEFAULT 0, 	
			eval4_grade_c2 integer DEFAULT 0, 	
			eval4_grade_c3 integer DEFAULT 0, 	
			eval4_grade_c4 integer DEFAULT 0, 	
			foot_consentement_paro integer DEFAULT 0, 	
			foot_reference_paro integer DEFAULT 0, 	
			PRIMARY KEY(id_protocoleurgent_cegep))	
		end;

