insert into t_system_codes (code, nom_fr, nom_an, ordre) select  'CRF001', 'Référent 1',  'Referral 1', 1 from dummy where not exists (select * from t_system_codes where code = 'CRF001');
insert into t_system_codes (code, nom_fr, nom_an, ordre) select  'CRF002', 'Référent 2',  'Referral 2', 2 from dummy where not exists (select * from t_system_codes where code = 'CRF002');
insert into t_system_codes (code, nom_fr, nom_an, ordre) select  'CRF003', 'Référent 3',  'Referral 3', 3 from dummy where not exists (select * from t_system_codes where code = 'CRF003');
Case When not exists ( select * from syscolumn inner join systable on syscolumn.table_id = systable.table_id where table_name = 't_introconcl' and column_name = 'textean') then Alter Table t_introconcl add textean varchar(5000) end;
Case When not exists ( select * from syscolumn inner join systable on syscolumn.table_id = systable.table_id where table_name = 't_introconcl' and column_name = 'titrean') then Alter Table t_introconcl add titrean varchar(30) end;
Case When not exists ( select * from syscolumn inner join systable on syscolumn.table_id = systable.table_id where table_name = 't_fusionpublipostage' and column_name = 'itemmenuan') then Alter Table t_fusionpublipostage add itemmenuan varchar(100) end;
Case When not exists ( select * from syscolumn inner join systable on syscolumn.table_id = systable.table_id where table_name = 't_histolettre' and column_name = 'code_referent') then Alter Table t_histolettre add code_referent varchar(6) end;
update t_fusionpublipostage set itemmenu = 'Numéro d''assurance maladie du patient' where itemmenu like 'Numéro d%assurance maladie du patient';  
update t_fusionpublipostage set itemmenu = 'Professionnel' where itemmenu='Spécialiste';  
update t_fusionpublipostage set itemmenu = 'Titre du professionnel' where itemmenu='Titre du spécialiste';  
update t_fusionpublipostage set itemmenu = 'Nom du professionnel' where itemmenu='Nom du spécialiste';  
update t_fusionpublipostage set itemmenu = 'Prénom du professionnel' where itemmenu='Prénom du spécialiste';  
update t_fusionpublipostage set itemmenu = 'Initiale du professionnel' where itemmenu='Initiale du spécialiste';  
update t_fusionpublipostage set itemmenuan = 'Patient' where itemmenu='Patient';  
update t_fusionpublipostage set itemmenuan = 'Appointment' where itemmenu='Rendez-vous';  
update t_fusionpublipostage set itemmenuan = 'Professional' where itemmenu='Professionnel';  
update t_fusionpublipostage set itemmenuan = 'Person' where itemmenu='Personne';  
update t_fusionpublipostage set itemmenuan = 'Today''s Date' where itemmenu='Date du jour';  
update t_fusionpublipostage set itemmenuan = 'Date' where itemmenu='Date';  
update t_fusionpublipostage set itemmenuan = 'Time' where itemmenu='Heure';  
update t_fusionpublipostage set itemmenuan = 'Day' where itemmenu='Jour';  
update t_fusionpublipostage set itemmenuan = 'Month' where itemmenu='Mois';  
update t_fusionpublipostage set itemmenuan = 'Year' where itemmenu='Année';  
update t_fusionpublipostage set itemmenuan = 'Responsible''s Salutation' where itemmenu='Salutation du responsable';  
update t_fusionpublipostage set itemmenuan = 'Responsible''s Last Name' where itemmenu='Nom du responsable';  
update t_fusionpublipostage set itemmenuan = 'Responsible''s First Name' where itemmenu='Prénom du responsable';  
update t_fusionpublipostage set itemmenuan = 'Responsible''s Address' where itemmenu='Adresse du responsable';  
update t_fusionpublipostage set itemmenuan = 'Responsible''s City' where itemmenu='Ville du responsable';  
update t_fusionpublipostage set itemmenuan = 'Responsible''s Province' where itemmenu='Province du responsable';  
update t_fusionpublipostage set itemmenuan = 'Responsible''s Postal Code' where itemmenu='Code postal du responsable';  
update t_fusionpublipostage set itemmenuan = 'Professional''s Title' where itemmenu='Titre du professionnel';  
update t_fusionpublipostage set itemmenuan = 'Professional''s Last Name' where itemmenu='Nom du professionnel';  
update t_fusionpublipostage set itemmenuan = 'Professional''s First Name' where itemmenu='Prénom du professionnel';  
update t_fusionpublipostage set itemmenuan = 'Professional''s Initial' where itemmenu='Initiale du professionnel';  
update t_fusionpublipostage set itemmenuan = 'Appointment Date' where itemmenu='Date rendez-vous';  
update t_fusionpublipostage set itemmenuan = 'Appointment Time' where itemmenu='Heure du rendez-vous';  
update t_fusionpublipostage set itemmenuan = 'Patient File Number' where itemmenu='Numéro de dossier du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Salutation' where itemmenu='Salutation patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Last Name' where itemmenu='Nom du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s First Name' where itemmenu='Prénom du patient';  
update t_fusionpublipostage set itemmenuan = 'Age' where itemmenu='Âge';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Gender' where itemmenu='Sexe du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Date of Birth' where itemmenu='Date de naissance du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Email' where itemmenu='Courriel du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Address' where itemmenu='Adresse du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s City' where itemmenu='Ville du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Province' where itemmenu='Province du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Postal Code' where itemmenu='Code postal du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Home Phone' where itemmenu='Téléphone maison du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Work Phone' where itemmenu='Téléphone bureau du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Cell Phone' where itemmenu='Cellulaire du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Other Phone' where itemmenu='Autre téléphone du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Social Insurance Number' where itemmenu='No. assurance sociale du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Health Insurance Number' where itemmenu='Numéro d''assurance maladie du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Account' where itemmenu='Compte du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Father' where itemmenu='Père du patient';  
update t_fusionpublipostage set itemmenuan = 'Patient''s Mother' where itemmenu='Mère du patient';  
update t_fusionpublipostage set itemmenuan = 'Laboratory Case' where itemmenu='Case de laboratoire';  
update t_fusionpublipostage set itemmenuan = 'Laboratory Case Number' where itemmenu='No cas de laboratoire';  
update t_fusionpublipostage set itemmenuan = 'Laboratory Case Date' where itemmenu='Date cas de laboratoire';  
update t_fusionpublipostage set itemmenuan = 'Hygiene Reminder' where itemmenu='Rappel hygiène';  
update t_fusionpublipostage set itemmenuan = 'Reminder Date' where itemmenu='Date rappel';  
update t_fusionpublipostage set itemmenuan = 'Referrer' where itemmenu='Référent';  
update t_fusionpublipostage set itemmenuan = 'Referrer''s Last Name' where itemmenu='Nom du référent';  
update t_fusionpublipostage set itemmenuan = 'Referrer''s First Name' where itemmenu='Prénom du référent';  
update t_fusionpublipostage set itemmenuan = 'Referrer''s Salutation' where itemmenu='Salutation du référent';  
update t_fusionpublipostage set itemmenuan = 'SMS' where itemmenu='SMS';  
update t_fusionpublipostage set itemmenuan = 'Confirmation Link' where itemmenu='Lien de confirmation';  
update t_fusionpublipostage set itemmenuan = 'Treatment Name' where itemmenu='Nom traitement';  
update t_fusionpublipostage set itemmenuan = 'Last Appointment' where itemmenu='Dernier rendez-vous';  
update t_fusionpublipostage set itemmenuan = 'Unsubscribe Link' where itemmenu='Lien de désabonnement';  
update t_fusionpublipostage set itemmenuan = 'Appointment Duration' where itemmenu='Durée du rendez-vous';  
update t_fusionpublipostage set itemmenuan = 'Confirmation Code' where itemmenu='Code de confirmation';  
update t_fusionpublipostage set itemmenuan = 'Referrer 2 Last Name' where itemmenu='Nom du référent 2';  
update t_fusionpublipostage set itemmenuan = 'Referrer 2 First Name' where itemmenu='Prénom du référent 2';  
update t_fusionpublipostage set itemmenuan = 'Referrer 2 Salutation' where itemmenu='Salutation du référent 2';  
update t_fusionpublipostage set itemmenuan = 'Referrer 3 Last Name' where itemmenu='Nom du référent 3';  
update t_fusionpublipostage set itemmenuan = 'Referrer 3 First Name' where itemmenu='Prénom du référent 3';  
update t_fusionpublipostage set itemmenuan = 'Referrer 3 Salutation' where itemmenu='Salutation du référent 3';  
