Case When not exists ( select * from syscolumn inner join systable on syscolumn.table_id = systable.table_id where table_name = 't_fusionpublipostage' and column_name = 'ordre') then Alter Table t_fusionpublipostage add ordre integer end;
INSERT INTO t_fusionpublipostage (itemmenu,champfusion,identifiant,requetesql,id_parent,itemmenuan, ordre) VALUES('Titre du professionnel (RDV)','%Spc_titre_rdv%','id_horrdvpat','select coalesce((select max(t_specialists.dr_titre) from t_useroptocl inner join t_specialists on t_useroptocl.id_user = t_specialists.id_user and t_useroptocl.typeuser = 1 where t_horrdvpat.id_optcol = t_useroptocl.id_optcol), (select max(t_specialists.dr_titre) from t_patients inner join t_specialists on t_patients.id_specialist = t_specialists.id_specialist where t_horrdvpat.id_patient = t_patients.id_patient), '''') from t_horrdvpat',(select max(id_parent) from t_fusionpublipostage where itemmenu = 'Titre du professionnel'),'Professional''s Title (Apt)', 11);
INSERT INTO t_fusionpublipostage (itemmenu,champfusion,identifiant,requetesql,id_parent,itemmenuan, ordre) VALUES('Nom du professionnel (RDV)','%Spc_nom_rdv%','id_horrdvpat','select coalesce((select max(t_specialists.dr_nom) from t_useroptocl inner join t_specialists on t_useroptocl.id_user = t_specialists.id_user and t_useroptocl.typeuser = 1 where t_horrdvpat.id_optcol = t_useroptocl.id_optcol), (select max(t_specialists.dr_nom) from t_patients inner join t_specialists on t_patients.id_specialist = t_specialists.id_specialist where t_horrdvpat.id_patient = t_patients.id_patient), '''') from t_horrdvpat',(select max(id_parent) from t_fusionpublipostage where itemmenu = 'Nom du professionnel'),'Professional''s Last Name (Apt)', 12);
INSERT INTO t_fusionpublipostage (itemmenu,champfusion,identifiant,requetesql,id_parent,itemmenuan, ordre) VALUES('Prénom du professionnel (RDV)','%Spc_prenom_rdv%','id_horrdvpat','select coalesce((select max(t_specialists.dr_prenom) from t_useroptocl inner join t_specialists on t_useroptocl.id_user = t_specialists.id_user and t_useroptocl.typeuser = 1 where t_horrdvpat.id_optcol = t_useroptocl.id_optcol), (select max(t_specialists.dr_prenom) from t_patients inner join t_specialists on t_patients.id_specialist = t_specialists.id_specialist where t_horrdvpat.id_patient = t_patients.id_patient), '''') from t_horrdvpat',(select max(id_parent) from t_fusionpublipostage where itemmenu = 'Prénom du professionnel'),'Professional''s First Name (Apt)', 13);
INSERT INTO t_fusionpublipostage (itemmenu,champfusion,identifiant,requetesql,id_parent,itemmenuan, ordre) VALUES('Initiales du professionnel (RDV)','%Spc_initiale_rdv%','id_horrdvpat','select coalesce((select max(t_specialists.init) from t_useroptocl inner join t_specialists on t_useroptocl.id_user = t_specialists.id_user and t_useroptocl.typeuser = 1 where t_horrdvpat.id_optcol = t_useroptocl.id_optcol), (select max(t_specialists.init) from t_patients inner join t_specialists on t_patients.id_specialist = t_specialists.id_specialist where t_horrdvpat.id_patient = t_patients.id_patient), '''') from t_horrdvpat',(select max(id_parent) from t_fusionpublipostage where itemmenu = 'Initiale du professionnel'),'Professional''s Initial (Apt)', 14);
update t_fusionpublipostage set ordre = 1 where champfusion = '%Spc_titre%';
update t_fusionpublipostage set ordre = 2 where champfusion = '%Spc_nom%';
update t_fusionpublipostage set ordre = 3 where champfusion = '%Spc_prenom%';
update t_fusionpublipostage set itemmenu = 'Initiales du professionnel', ordre = 4 where champfusion = '%Spc_initiale%';
